baseurl = "/"
languageCode = "en-us"
title = "Matt McNew"
theme = "hugo-strata-theme"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
#googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

pygmentsStyle= "manni"
pygmentsCodeFences=true

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Matt McNew"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.recentposts]
	    hide = true


	[params.sidebar]
		# Replace the  with a picture of your own under static/images
		avatar = "mcnew.gif"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Matt McNew** <br>  Software Engineer <br> Occasional Traveler"
		# The icons will be shown if you enter your username
		twitter = "matthewmcnew"
		github = "matthewmcnew"
#		dribbble = ""
#		facebook = ""
#		googleplus = ""
#		flickr = ""
		linkedin = "mattmcnew"

#		copyright = [
#			"&copy; John Doe",
#			"Design: [HTML5 UP](//html5up.net)",
#			"Demo Images: [Unsplash](//unsplash.com/)"
#		]

	[params.about]
		hide  = false
		title = "Hi, I'm Matt McNew"
		content = "I'm a Software Engineer at [Pivotal](http://www.pivotal.io/). Check out my [Github](http://wwww.github.com/matthewmcnew). </br> I maintain a statically typed typescript mocking library: [Safe Mock](/post/safe-mock) </br> I like to talk about software. [My Presentations](/categories/presentations/) </br> I love to travel. Check out my travel photos at: [trackmatt.com](http://trackmatt.com) "


	[params.portfolio]
		hide  = true
		title = "Blah"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Not A Thing"
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		hide  = true
		title = "Matthew McNew"
		content = "Yahoo! Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "Please Don't :)"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "me@mattmcnew.com"

		[params.contact.form]
		    hide = true
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Posts"
	url  = "post/"
	weight = 10

[[menu.main]]
	name = "My Travels"
	url  = "http://trackmatt.com/"
	weight = 0